### PR TITLE
update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by wanlyg**
Fixed incomplete display of Android 11 application list

### CODE REVIEW

**Comment by akhilkedia** [comment]
Thanks for the PR.
I was holding off on pushing on update for Android 11, as I couldn't test if other features were working.
By any chance, did you test the app after this? If yes, do other apps translate?

**Comment by roseryel** [comment]
i can confirm the only issue i had on A11 was just application list. the translation itself works just fine. tried with telegraph, vk, and coolapk.

**Comment by wanlyg** [comment]
I'm sorry, due to compatibility issues, I failed to compile locally.  However, I decompile the latest version and add permissions, although sometimes the translation is not ideal, but it works @akhilkedia

**Comment by akhilkedia** [comment]
I will upload the latest version with your fixed permissions to Play store and xposed repo.

**Pull request merged**
